name: "RSS"

services:
  freshrss:
    image: freshrss/freshrss@sha256:48b63b9bc3d042a1301c32971b01af8841c7f059b452589c5bf77f475ba44c61
    container_name: freshrss
    networks:
      - proxy-freshrss
      - freshrss-rss-bridge
    logging:
      options:
        max-size: 10m
    volumes:
      - /root/data/freshrss/data:/var/www/FreshRSS/data
      - /root/data/freshrss/extensions:/var/www/FreshRSS/extensions
    env_file:
      - ./.env.rss
    environment:
      TZ: Europe/Paris
      CRON_MIN: "3,33"
      INTERNAL_HOST_ALLOWLIST: "rss-bridge:80"
    restart: unless-stopped

  rss-bridge:
    image: rssbridge/rss-bridge@sha256:239c81e07fb09a3222970cc94c32581ff82635bf0252813a6f4ee876251ee39f
    container_name: rss-bridge
    networks:
      - freshrss-rss-bridge
      - rss-bridge-egress
    volumes:
      - /root/data/rss-bridge:/config
    env_file:
      - ./.env.rss
    restart: unless-stopped
