name: "RSS"

services:
  freshrss:
    image: freshrss/freshrss@sha256:258b8edfc8a76a61f60d2d6a14d8f8d12495d78abf38646a2137612dfa264a21
    container_name: freshrss
    networks:
      - proxy-freshrss
    logging:
      options:
        max-size: 10m
    volumes:
      - /root/data/freshrss/data:/var/www/FreshRSS/data
      - /root/data/freshrss/extensions:/var/www/FreshRSS/extensions
    env_file:
      - ./.env.rss
    environment:
      TZ: Europe/Paris
      CRON_MIN: "3,33"
    restart: unless-stopped

  rss-bridge:
    image: rssbridge/rss-bridge@sha256:606896116558c57e3d381dec6874457f7a69216103d77c78b5bd38b92b251902
    container_name: rss-bridge
    networks:
      - proxy-rss-bridge
    volumes:
      - /root/data/rss-bridge:/config
    env_file:
      - ./.env.rss
    restart: unless-stopped
