name: "LibreChat"

services:
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.multi
    #   target: api-build
    image: ghcr.io/danny-avila/librechat-dev-api:latest@sha256:dee4315fff7536abf58caa1081b44dd9381d6f30740848d54d98224eb8d2987a
    container_name: librechat-api
    networks:
      - proxy-librechat
      - librechat-mongodb
      - librechat-meilisearch
      - librechat-rag
      - librechat-prowlarr
    # ports:
    #   - 3080:3080
    depends_on:
      - mongodb
      - rag_api
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - /root/data/librechat/config/.env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      - type: bind
        source: /root/data/librechat/config/librechat.yaml
        target: /app/librechat.yaml
      - /root/data/librechat/data/images:/app/client/public/images
      - /root/data/librechat/data/logs:/app/api/logs

  mongodb:
    container_name: librechat-mongodb
    networks:
      - librechat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo@sha256:5d7043a4ffe02b9ed1b6e0bab057546981af5ca0a79107e9c461e49bc44c0a7b
    restart: always
    volumes:
      - /root/data/librechat/data/data-node:/data/db
    command: mongod --noauth

  meilisearch:
    container_name: librechat-meilisearch
    networks:
      - librechat-meilisearch
    image: getmeili/meilisearch:v1.53.2@sha256:c94e58ca09662dd6e65e8f1b0fd145767be3da7d5422a863a27b8d2b68e090c9
    restart: always
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    env_file:
      - /root/data/librechat/config/.env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - /root/data/librechat/data/meili_data_v1.12:/meili_data

  vectordb:
    image: ankane/pgvector:latest@sha256:956744bd14e9cbdf639c61c2a2a7c7c2c48a9c8cdd42f7de4ac034f4e96b90f8
    container_name: librechat-vectordb
    networks:
      - rag-vectordb
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - /root/data/librechat/data/postgress:/var/lib/postgresql/data

  rag_api:
    container_name: librechat-rag-api
    networks:
      - librechat-rag
      - rag-vectordb
      - rag-egress
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest@sha256:a62ce2221b43a9bb57fa6cb733e7047c80132960272c33d5704028f3071a1251
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - /root/data/librechat/config/.env
