name: "MCP"

services:
  prowlarr-mcp:
    image: ghcr.io/elcaten/prowlarr-mcp:latest@sha256:32eeaa0d56cb811abc77008a2dcacc2f1e48db2309bde9997385a0c5b8a1aa79
    container_name: prowlarr-mcp
    restart: unless-stopped
    expose:
      - "8080"
    env_file:
      - ./.env.mcp
    environment:
      FASTMCP_TRANSPORT: http
      FASTMCP_HOST: 0.0.0.0
      FASTMCP_PORT: "8080"
