name: "Alternative UIs"

services:
  redlib:
    image: ghcr.io/cycneuramus/containers:redlib@sha256:4b607fd58f2c170d9bbf073bfedbe570c5b6f29c7e72b3a2285e86d5c7f98af9
    container_name: redlib
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - REDLIB_DEFAULT_USE_HLS=on
      - REDLIB_DEFAULT_SHOW_NSFW=on

  iSponsorBlockTV:
    container_name: iSponsorBlockTV
    image: ghcr.io/dmunozv04/isponsorblocktv@sha256:d1e876636754fb2b54490feebe3af4a321f7f2a932a2d57b67b2a667eea40823
    restart: unless-stopped
    volumes:
      - /root/data/iSponsorBlockTV:/app/data
