name: "Infra"

services:
  caddy:
    build:
      context: /root/data/caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /root/data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /root/data/caddy/data:/data
      - /root/data/caddy/config:/config
      - /root/data/caddy/logs:/var/log/caddy
      - /root/data/caddy/cloudflare:/etc/cloudflare

  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:4.39.4@sha256:64b356c30fd817817a4baafb4dbc0f9f8702e46b49e1edb92ff42e19e487b517
    restart: "unless-stopped"
    depends_on:
      - redis
    volumes:
      - /root/data/authelia:/config

  redis:
    image: redis@sha256:8a1efc5f479551822b47424ccae982026b633f28818eab0387348120a61e10e2
    restart: unless-stopped
    container_name: redis
    volumes:
      - /root/data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic@sha256:f57f5ce0af50819024a9a57bc54904260118a6481c650e26c985b63138d3ba29
    container_name: borgmatic
    volumes:
      - /root:/mnt/source
      - /root/data/borgmatic/repository:/mnt/borg-repository
      - /root/data/borgmatic/borgmatic.d:/etc/borgmatic.d/
      - /root/data/borgmatic/.config/borg:/root/.config/borg
      - /root/data/borgmatic/.ssh:/root/.ssh
      - /root/data/borgmatic/.cache/borg:/root/.cache/borg
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
